version: "3"
services:
  auth-web:
    build: docker/nginx
    ports:
      - 127.0.0.1:80:80
# uncomment lines if you need local files share
    volumes:
       - ./:/app/:cached

  auth-backend:
    build: .
    volumes:
       - auth-store:/app/storage # comment this line if you need local files share
       - ./:/app/:cached # uncomment this line if you need local files share

  auth-worker:
    build: .
    volumes:
       - auth-store:/app/storage # comment this line if you need local files share
       - ./:/app/:cached # uncomment this line if you need local files share
    command: ['./bin/hello-worker']

  rabbitmq:
    image: rabbitmq:3.7-management-alpine
    ports:
      -  127.0.0.1:15672:15672
      -  127.0.0.1:5672:5672
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq

  database:
    image: percona:5.7
    environment:
       - MYSQL_DATABASE=social
       - MYSQL_USER=social
       - MYSQL_PASSWORD=social
       - MYSQL_RANDOM_ROOT_PASSWORD=1

volumes:
  auth-store:
  rabbitmq-data:
